#docker-compose.yml

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
        - PORT=3001
        - WATCHPACK_POLLING=true
        - CHOKIDAR_USEPOLLING=true
        - FAST_REFRESH=true
    stdin_open: true
    tty: true
